# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(upload_to='news', verbose_name='Фото')),
                ('title', models.CharField(max_length=150, unique_for_date='posted', verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2016, 10, 28, 22, 49, 28, 379824), verbose_name='Опублікована')),
            ],
            options={
                'verbose_name': 'новину',
                'verbose_name_plural': 'новини',
                'ordering': ['-posted'],
            },
        ),
    ]
