# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 10:26
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', autoslug.fields.AutoSlugField(unique=True, verbose_name='Адресна строка')),
            ],
            options={
                'verbose_name_plural': 'категорії',
                'verbose_name': 'категорія',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(upload_to='news', verbose_name='Фото')),
                ('title', models.CharField(max_length=150, unique_for_date='posted', verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(unique=True, verbose_name='Адресна строка')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2016, 11, 22, 12, 26, 11, 999640), verbose_name='Опублікована')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Оберіть категорію')),
            ],
            options={
                'verbose_name_plural': 'новини',
                'verbose_name': 'новину',
                'ordering': ['-posted'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва тегу')),
                ('slug', autoslug.fields.AutoSlugField(unique=True, verbose_name='Адресна строка')),
            ],
            options={
                'verbose_name_plural': 'теги',
                'verbose_name': 'тег',
            },
        ),
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.ManyToManyField(to='news.Tag', verbose_name='Оберіть теги для статті'),
        ),
    ]
