# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161028_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 10, 28, 23, 17, 22, 26769), verbose_name='Опублікована'),
        ),
    ]
