# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161028_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 10, 29, 18, 45, 36, 653415), verbose_name='Опублікована'),
        ),
    ]
