# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20161030_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=django_resized.forms.ResizedImageField(upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 10, 30, 10, 54, 3, 784959), verbose_name='Опублікована'),
        ),
    ]
