# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20161030_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 10, 30, 15, 49, 10, 770050), verbose_name='Опублікована'),
        ),
    ]
