# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20161030_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 10, 30, 17, 42, 48, 224032), verbose_name='Опублікована'),
        ),
    ]
