# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 15:45
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='850x850',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='img', verbose_name='image_field'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
