# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 15:50
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20161029_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='850x850',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='img', verbose_name='850x850'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('800x800', '0x0', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
