# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 15:52
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20161029_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='img'),
        ),
    ]
