# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 08:47
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20161029_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='employees'),
        ),
    ]
