# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(choices=[('CO', 'Головний офіс'), ('RO', 'Регіональний офіс')], default='Регіональний офіс', max_length=2)),
                ('type_sity', models.CharField(choices=[('1', 'м.'), ('2', 'смт.'), ('3', 'с.')], default='м.', max_length=1)),
                ('post_index', models.CharField(max_length=5, verbose_name='Поштовий індекс')),
                ('country_name', models.CharField(default='Україна', max_length=150, verbose_name='Країна')),
                ('region', models.CharField(default='Хмельницька', max_length=150, verbose_name='Область')),
                ('sity_office', models.CharField(default='Хмельницький', max_length=150, verbose_name='Населений пункт')),
                ('street', models.CharField(max_length=150, verbose_name='Вулиця')),
                ('building', models.CharField(max_length=10, verbose_name='Номер будинку')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
